id: P429B59C9
initial_creation_type: ocr
source_metadata:
  volumes:
    ad53d379749b4aef97bd805697151aee:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: ཆོས་ཐམས་ཅད་རང་བཞིན་མེད་པ་ཉིད་དུ་གྲུབ་པ།
      total_pages: 1557
      volume_number: 62
